# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up MySQL
        run: choco install mysql --force
        env:
          MYSQL_SERVICE_NAME: "mysql"

      - name: Start MySQL
        run: |
         powershell.exe -Command "Start-Service -Name mysql" || powershell.exe -Command "Restart-Service -Name mysql"

      - name: Configure MySQL root password and create database
        run: |
          powershell.exe -Command "while (!(mysqladmin ping -u root -p123456 -h localhost -P 3306 -timeout 5s)); do { Start-Sleep -Seconds 1 }; done; mysql -u root -p123456 -h localhost -P 3306 -e 'CREATE DATABASE wp_emc;'"

      - name: Import database
        run: |
         while (!(mysqladmin ping -u root -prootpassword -h localhost -P 3306 --silent)); do { Start-Sleep -Seconds 1 }; done; mysql -u root -p123456 -h localhost -P 3306 wordpress < ${{ github.workspace }}\backup.sql

      - name: Run PHP-CGI
        run: |
            Start-Process -FilePath "php-cgi.exe" -ArgumentList "-b 127.0.0.1:9000" -NoNewWindow -PassThru

      # Runs a set of commands using the runners shell
      - name: Run nginx
        run: |
            cd nginx\nginx-1.27.0
            start nginx
      - name: Run nginx reverse proxy
        run: |
            cd nginx-reverseproxy\nginx-1.27.0
            start nginx
      - name: Test WordPress Admin Login
        run: |
          curl -s http://localhost
