# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: wp_emc
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Wait for MySQL to be healthy
        run: |
              echo "Waiting for MySQL to start..."
              for i in {1..30}; do
                if mysqladmin ping -h 127.0.0.1 --silent; then
                  echo "MySQL is up and running!"
                  break
                fi
                echo "Waiting for MySQL..."
                sleep 2
              done

      - name: Run MySQL commands
        run: |
          mysql -h 127.0.0.1 -u root -p123456 -e "SHOW DATABASES;"
        shell: bash

      - name: Run PHP-CGI
        run: |
            Start-Process -FilePath "php-cgi.exe" -ArgumentList "-b 127.0.0.1:9000" -NoNewWindow -PassThru

      # Runs a set of commands using the runners shell
      - name: Run nginx
        run: |
            cd nginx\nginx-1.27.0
            start nginx
      - name: Run nginx reverse proxy
        run: |
            cd nginx-reverseproxy\nginx-1.27.0
            start nginx
      - name: Test WordPress Admin Login
        run: |
          curl -s localhost
