name: CI/CD Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install MySQL
      run: choco install mysql

    - name: Start MySQL
      run: |
        net start mysql
        mysqladmin -u root password "123456"
        mysql -u root -p123456 -e "CREATE DATABASE wp_emc;"

    
    - name: Kiểm tra thư mục PHP-CGI
      run: |
        Write-Output "Danh sách tệp trong thư mục php:"
        Get-ChildItem ./php

    - name: Khởi động PHP-CGI
      run: |
        Write-Output "Đang khởi động PHP-CGI..."
        Start-Process -FilePath "./php/php-cgi.exe" -ArgumentList "-b 127.0.0.1:9000" -NoNewWindow -PassThru
        Start-Sleep -Seconds 5
        $process = Get-Process | Where-Object { $_.Path -eq (Resolve-Path ./php/php-cgi.exe) }
        if ($process) {
          Write-Output "PHP-CGI đang chạy"
        } else {
          Write-Error "PHP-CGI khởi động thất bại"
        }
    - name: start Nginx
      run: |
        cd nginx\nginx-1.27.0
        start nginx
  
    - name: start Nginx Reverse proxy
      run: |
        cd nginx-reverseproxy\nginx-1.27.0
        start nginx
        
    - name: Run Tests
      run: |
        # Run additional tests to verify WordPress functionality
        # ví dụ kiểm tra bằng cURL đến các trang khác nhau
        curl -s http://localhost --output /dev/null && echo "OK" || echo "Failed"
       
