name: CI/CD Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    - name: Kiểm tra thư mục PHP-CGI
      run: |
        Write-Output "Danh sách tệp trong thư mục php:"
        Get-ChildItem ./php

    - name: Khởi động PHP-CGI
      run: |
        Write-Output "Đang khởi động PHP-CGI..."
        Start-Process -FilePath "./php/php-cgi.exe" -ArgumentList "-b 127.0.0.1:9000" -NoNewWindow -PassThru
        Start-Sleep -Seconds 5
        $process = Get-Process | Where-Object { $_.Path -eq (Resolve-Path ./php/php-cgi.exe) }
        if ($process) {
          Write-Output "PHP-CGI đang chạy"
        } else {
          Write-Error "PHP-CGI khởi động thất bại"
        }
    - name: start Nginx
      run: |
        cd nginx\nginx-1.27.0
        start nginx
    
    - name: start Nginx Reverse proxy
      run: |
        cd nginx-reverseproxy\nginx-1.27.0
        start nginx
    - name: Kiểm tra nội dung index.html
      run: |
        $indexContent = Get-Content -Path "./index.html"
        if ($indexContent -match '<a.*href="http://localhost".*>') {
          Write-Output "index.html chứa thẻ a với href là http://localhost"
        } else {
          Write-Error "index.html không chứa thẻ a với href là http://localhost"
          }
    - name: Kiểm tra tên database trong wp-config.php
      run: |
        $wpConfig = Get-Content -Path "nginx/nginx-1.27.0/html/wordpress/wp-config.php" -Raw
        if ($wpConfig -match "'DB_NAME', '(wp_emc)'") {
          Write-Output "Tên database trong wp-config.php là wp_emc"
        } else {
          Write-Error "Tên database trong wp-config.php không phải là wp_emc"
          }
    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
          server: files.000webhost.com
          username: vantruong123123
          password: Anhkobietai123~
          port: 21
          protocol: ftp
          local-dir: ./nginx/nginx-1.27.0/html/wordpress/
          server-dir: ./public_html/
    #- name: Run Tests
      #run: |
        # Run additional tests to verify WordPress functionality
        # ví dụ kiểm tra bằng cURL đến các trang khác nhau
       # curl -s http://localhost --output /dev/null && echo "OK" || echo "Failed"
       
